services:
  horses_db:
    container_name: horse_network_db
    image: postgres
    
    environment:
      POSTGRES_DB: ${HORSE_DATABASE_NAME}
      POSTGRES_USER: ${HORSE_DATABASE_USER}
      POSTGRES_PASSWORD: ${HORSE_DATABASE_PASS}

    ports:
      - ${HORSE_DATABASE_PORT}:5432